# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: “Process+”
description: > # this means to ignore newlines until "email:"
   You’re doing it wrong.

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/bbc-whiteboard-osos.jpg"

name: ‘Tim Cunnane’
author: ‘Tim Cunnane’
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://processpl.us” # the base hostname & protocol for your site
baseurl: "http://processpl.us"
#used to display twitter cards
twitter_handle: ‘@timcunnane’

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
	url:	https://twitter.com/timcunnane
	desc: Follow me on twitter
	share_url: http://twitter.com/share
	share_title: ?text=
	share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
	url:	https://github.com/tcunnane
	desc:	Fork me on github
	share_url:
	share_title:
	share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link: